namespace: "it4smart"
name: "application"
version: "0.1.0"
readme: README.md
authors:
  - hack3d (github.com/hack3d)
description: A collection of roles to deploy applications like podman, dhcp-server, pdc
license_file: LICENSE
repository: https://github.com/IT4smart/ansible_collection_application
homepage: https://github.com/IT4smart/ansible_collection_application
issues: https://github.com/IT4smart/ansible_collection_application/issues
build_ignore:
  - ".gitignore"
