FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y systemd sudo python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN echo "ubuntu ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ubuntu && \
    chmod 0440 /etc/sudoers.d/ubuntu

USER ubuntu 

CMD ["tail -f /dev/null"]
